In [90]:
# Import Libraries
import pandas as pd
import numpy as np

In [91]:
# Q1. Pandas version: What version of Pandas did you install?
pd.__version__

'2.3.1'

In [92]:
# Download CSV file from GitHub -- only necessary to run once
# !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

In [93]:
# Read CSV file
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [94]:
# Print head
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [95]:
# Q2. Records count: How many records are in the dataset?
len(df)

9704

In [96]:
# Q3. Fuel types: How many fuel types are presented in the dataset?
df['fuel_type'].nunique()

2

In [97]:
# Q4. Missing values: How many columns in the dataset have missing values?
df.isnull().sum()[df.isnull().sum() > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [98]:
# Q5. Max fuel efficiency: What's the maximum fuel efficiency of cars from Asia?
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [99]:
# Q6. Median value of horsepower
# Find the median value of the horsepower column in the dataset.
hp_median = df['horsepower'].median()
hp_median

np.float64(149.0)

In [100]:
# Q6. Median value of horsepower
# Next, calculate the most frequent value of the same horsepower column.
#df['horsepower'].value_counts()
most_freq_hp = df['horsepower'].mode()[0]
most_freq_hp

np.float64(152.0)

In [101]:
# Q6. Median value of horsepower
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(most_freq_hp)
df['horsepower'].isnull().sum()

np.int64(0)

In [102]:
# Q6. Median value of horsepower
# Now, calculate the median value of horsepower once again.
hp_median_new = df['horsepower'].median()
hp_median_new

np.float64(152.0)

In [103]:
# Q6. Median value of horsepower: Has it changed?
hp_change = (
    "Yes, it increased" if hp_median_new > hp_median
    else "Yes, it decreased" if hp_median_new < hp_median
    else "No"
)

hp_change

'Yes, it increased'

In [104]:
# Q7. Sum of weights
# Select all the cars from Asia
df = df.loc[df['origin'] == 'Asia']

In [105]:
# Q7. Sum of weights
# Select only columns vehicle_weight and model_year
df = df[['vehicle_weight', 'model_year']]
df

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [106]:
# Q7. Sum of weights
# Select the first 7 values
df = df.head(7)

In [107]:
# Q7. Sum of weights
# Get the underlying NumPy array. Let's call it X.
X = df.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [108]:
# Q7. Sum of weights
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [109]:
# Q7. Sum of weights
# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [110]:
# Q7. Sum of weights
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [113]:
# Q7. Sum of weights
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [114]:
# Q7. Sum of weights: What's the sum of all the elements of the result?
total = np.sum(w)
total

np.float64(0.5187709081074016)